In [102]:
import numpy as np
import pandas as pd

In [103]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  6  5
y  4  9

In [104]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('zt'),
    columns=list('ab')
)

df2

   a  b
z  9  7
t  9  7

## Concaténer des `Series` ou `DataFrames` avec `pd.concat()`

In [105]:
pd.concat([df1, df2])

   a  b
x  6  5
y  4  9
z  9  7
t  9  7

In [106]:
s1 = pd.Series([30, 35], index=['alice', 'bob'])
s2 = pd.Series([32, 22, 29], index=['bill', 'alice', 'jo'])

In [107]:
s1

alice    30
bob      35
dtype: int64

In [108]:
s2

bill     32
alice    22
jo       29
dtype: int64

In [109]:
try:
    pd.concat([s1, s2], verify_integrity=True)
except ValueError as e:
    print(f"Erreur de concaténation:\n{e}")

Erreur de concaténation:
Indexes have overlapping values: Index(['alice'], dtype='str')

In [110]:
s1 = pd.Series(range(1000), index=[chr(x) for x in  range(1000)])
s1.tail()

ϣ    995
Ϥ    996
ϥ    997
Ϧ    998
ϧ    999
dtype: int64

In [111]:
s2 = pd.Series(range(1000), index=[chr(x+2000) for x in range(1000)])
s2.tail()

ள    995
ழ    996
வ    997
ஶ    998
ஷ    999
dtype: int64

In [112]:
%timeit pd.concat([s1, s2], verify_integrity=True)

558 μs ± 107 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [113]:
%timeit pd.concat([s1, s2])

The slowest run took 4.05 times longer than the fastest. This could mean that an intermediate result is being cached.
253 μs ± 146 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

### Changer le sens de la concaténation pour une orientation horizontale

In [114]:
df1 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('ab')
)

df1

   a  b
x  5  9
y  3  5

In [115]:
df2 = pd.DataFrame(np.random.randint(1, 10, size=(2, 2)),
    index=list('xy'),
    columns=list('cd')
)

df2

   c  d
x  2  4
y  5  4

In [116]:
pd.concat([df1, df2], axis=1)

   a  b  c  d
x  5  9  2  4
y  3  5  5  4

In [117]:
pd.concat([df1, df2])

     a    b    c    d
x 5.00 9.00  NaN  NaN
y 3.00 5.00  NaN  NaN
x  NaN  NaN 2.00 4.00
y  NaN  NaN 5.00 4.00

In [118]:
pd.concat([df1, df2], join='inner')

Empty DataFrame
Columns: []
Index: [x, y, x, y]

In [119]:
pd.concat([df1, df2], axis=1).reindex(['x'])

   a  b  c  d
x  5  9  2  4

In [120]:
pd.concat([df1, df2], axis=1).reindex(['y'])

   a  b  c  d
y  3  5  5  4

In [121]:
pd.concat([df1, df2], axis=1).reindex(df2.columns, axis=1)

   c  d
x  2  4
y  5  4

In [122]:
pd.concat([df1, df2], axis=1).reindex(['a', 'b'], axis=1)

   a  b
x  5  9
y  3  5

## Jointure des DataFrames avec `pd.merge()`

Par défaut, `merge` fait un **inner join**

In [123]:
df1 = pd.DataFrame({'personnel': ['Bob', 'Lisa', 'Sue'],
                    'groupe': ['SAF', 'R&D', 'RH']})

df1

  personnel groupe
0       Bob    SAF
1      Lisa    R&D
2       Sue     RH

In [124]:
df2 = pd.DataFrame({'personnel': ['Lisa', 'Bob', 'Sue'],
                    'date embauche': ['2004', '2008', '2014']})

df2

  personnel date embauche
0      Lisa          2004
1       Bob          2008
2       Sue          2014

In [125]:
pd.merge(df1, df2)

  personnel groupe date embauche
0       Bob    SAF          2008
1      Lisa    R&D          2004
2       Sue     RH          2014


Il existe trois type de merges :

- one-to-one, c’est le merge lorqu’il n’y a pas de labels dupliqués dans les colonnes utilisées comme critère de merge ;

- many-to-one, c’est le merge lorsque l’une des deux colonnes contient des labels dupliqués, dans ce cas, on applique la stratégie one-to-one pour chaque label dupliqué, donc les entrées dupliquées sont préservées ;

- many-to-many, c’est la stratégie lorsqu’il y a des entrées dupliquées dans les deux colonnes. Dans ce cas, on fait un produit cartésien des lignes.

In [126]:
df1 = pd.DataFrame({'patient': ['Bob', 'Lisa', 'Sue'],
                    'repas': ['SS', 'SS', 'SSR']})
df1

  patient repas
0     Bob    SS
1    Lisa    SS
2     Sue   SSR

In [127]:
df2 = pd.DataFrame({'repas': ['SS', 'SSR'],
                    'explication': ['sans sel', 'sans sucre']})
df2

  repas explication
0    SS    sans sel
1   SSR  sans sucre

In [128]:
pd.merge(df1, df2)

  patient repas explication
0     Bob    SS    sans sel
1    Lisa    SS    sans sel
2     Sue   SSR  sans sucre

In [129]:
df1 = pd.DataFrame({'patient': ['Bob', 'Lisa', 'Sue'],
                    'repas': ['SS', 'SS', 'SSR']})

df1

  patient repas
0     Bob    SS
1    Lisa    SS
2     Sue   SSR

In [130]:
df2 = pd.DataFrame({'repas': ['SS', 'SS', 'SSR'],
                    'explication': ['sans sel', 'légumes', 'sans sucre']})

df2

  repas explication
0    SS    sans sel
1    SS     légumes
2   SSR  sans sucre

In [131]:
pd.merge(df1, df2)

  patient repas explication
0     Bob    SS    sans sel
1     Bob    SS     légumes
2    Lisa    SS    sans sel
3    Lisa    SS     légumes
4     Sue   SSR  sans sucre

In [132]:
df1 = pd.DataFrame({'employee': ['Bob', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'HR']})

df1

  employee        group
0      Bob   Accounting
1     Lisa  Engineering
2      Sue           HR

In [133]:
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Sue'],
                    'hire_date': [2004, 2008, 2014]})

df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2      Sue       2014

In [134]:
pd.merge(df1, df2, on='employee')

  employee        group  hire_date
0      Bob   Accounting       2008
1     Lisa  Engineering       2004
2      Sue           HR       2014

In [135]:
df1 = pd.DataFrame({'employee': ['Bob', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'HR']})
df1

  employee        group
0      Bob   Accounting
1     Lisa  Engineering
2      Sue           HR

In [136]:
df2 = pd.DataFrame({'name': ['Lisa', 'Bob', 'Sue'],
                    'hire_date': [2004, 2008, 2014]})
df2

   name  hire_date
0  Lisa       2004
1   Bob       2008
2   Sue       2014

In [137]:
m = pd.merge(df1, df2, left_on='employee', right_on='name')
m

  employee        group  name  hire_date
0      Bob   Accounting   Bob       2008
1     Lisa  Engineering  Lisa       2004
2      Sue           HR   Sue       2014

### Supprimer une colonne

In [138]:
m.drop('name', axis=1)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Lisa  Engineering       2004
2      Sue           HR       2014

### Merge externe, à gauche et à droite

In [139]:
df1 = pd.DataFrame({'name': ['Bob', 'Lisa', 'Sue'],
                    'pulse': [70, 63, 81]})
df1

   name  pulse
0   Bob     70
1  Lisa     63
2   Sue     81

In [140]:
df2 = pd.DataFrame({'name': ['Eric', 'Bob', 'Marc'],
                    'weight': [60, 100, 70]})
df2

   name  weight
0  Eric      60
1   Bob     100
2  Marc      70

In [141]:
pd.merge(df1, df2)

  name  pulse  weight
0  Bob     70     100

In [142]:
pd.merge(df1, df2, how='outer')

   name  pulse  weight
0   Bob  70.00  100.00
1  Eric    NaN   60.00
2  Lisa  63.00     NaN
3  Marc    NaN   70.00
4   Sue  81.00     NaN

In [143]:
pd.merge(df1, df2, how='left')

   name  pulse  weight
0   Bob     70  100.00
1  Lisa     63     NaN
2   Sue     81     NaN

In [144]:
pd.merge(df1, df2, how='right')

   name  pulse  weight
0  Eric    NaN      60
1   Bob  70.00     100
2  Marc    NaN      70

## Regrouper des DataFrames avec `pd.groupby()`

In [145]:
import seaborn as sns

In [146]:
titanic = sns.load_dataset('titanic').loc[:, ['survived', 'sex', 'class']]

titanic.head(10)

   survived     sex   class
0         0    male   Third
1         1  female   First
2         1  female   Third
3         1  female   First
4         0    male   Third
5         0    male   Third
6         0    male   First
7         0    male   Third
8         1  female   Third
9         1  female  Second

In [147]:
titanic.shape

(891, 3)

In [148]:
titanic.loc[:, 'survived'].mean()

np.float64(0.3838383838383838)

In [149]:
titanic.loc[titanic.loc[:, 'class']=='First','survived'].mean()

np.float64(0.6296296296296297)

In [150]:
titanic.groupby('class')

In [151]:
g = titanic.groupby(['class', 'sex']).mean()

g

               survived
class  sex
First  female      0.97
       male        0.37
Second female      0.92
       male        0.16
Third  female      0.50
       male        0.14

In [152]:
g.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

In [153]:
d = pd.DataFrame({'key': list('ABCABC'), 'val': range(6)})
d

  key  val
0   A    0
1   B    1
2   C    2
3   A    3
4   B    4
5   C    5

`groupby` produit un nouvel objet de groupe, qui permet d'appliquer des opérations sur chaque groupe de lignes.

In [154]:
g = d.groupby('key')
g

In [155]:
g.sum()

     val
key
A      3
B      5
C      7

In [156]:
g = d.groupby('key', as_index=False)
g.sum()

  key  val
0   A    3
1   B    5
2   C    7

In [157]:
d = pd.DataFrame({'key': list('ABCABC'),
                  'val1': range(6),
                  'val2' : range(100, 106)})
d

  key  val1  val2
0   A     0   100
1   B     1   101
2   C     2   102
3   A     3   103
4   B     4   104
5   C     5   105

In [158]:
g = d.groupby('key')

g.groups donne accès au dictionnaire des groupes, les clefs sont le nom du groupe et les valeurs les index des lignes
appartenant au groupe.

In [159]:
g.groups

{'A': [0, 3], 'B': [1, 4], 'C': [2, 5]}

In [160]:
g.get_group('A')

  key  val1  val2
0   A     0   100
3   A     3   103

In [161]:
g.sum()['val2']

key
A    203
B    205
C    207
Name: val2, dtype: int64

In [162]:
g['val2'].sum()

key
A    203
B    205
C    207
Name: val2, dtype: int64

On peut également itérer sur les groupes avec un boucle for classique

In [163]:
tips = sns.load_dataset("tips")

In [164]:
tips.head()

   total_bill  tip     sex smoker  day    time  size
0       16.99 1.01  Female     No  Sun  Dinner     2
1       10.34 1.66    Male     No  Sun  Dinner     3
2       21.01 3.50    Male     No  Sun  Dinner     3
3       23.68 3.31    Male     No  Sun  Dinner     2
4       24.59 3.61  Female     No  Sun  Dinner     4

In [165]:
g = tips.groupby('day')
g.groups

{'Thur': [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 243], 'Fri': [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 220, 221, 222, 223, 224, 225, 226], 'Sat': [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 168, 169, 170, 171, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242], 'Sun': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 112, 113, 114, 115, 116, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]}

In [166]:

for (group, index) in g:
    print(f"On {group} the mean tip is {index['tip'].mean():.3}")

On Thur the mean tip is 2.77
On Fri the mean tip is 2.73
On Sat the mean tip is 2.99
On Sun the mean tip is 3.26

on groupe par jour et on extrait uniquement la colonne 'total_bill' pour chaque groupe

In [167]:
g = tips.groupby('day')['total_bill']

## Fonction dispatch

on demande à pandas d'afficher les float avec seulement deux chiffres après la virgule

In [168]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [169]:
g.describe()

      count  mean  std  min   25%   50%   75%   max
day
Thur  62.00 17.68 7.89 7.51 12.44 16.20 20.16 43.11
Fri   19.00 17.15 8.30 5.75 12.09 15.38 21.75 40.17
Sat   87.00 20.44 9.48 3.07 13.91 18.24 24.74 50.81
Sun   76.00 21.41 8.83 7.25 14.99 19.63 25.60 48.17

Il y a tout de même un grand nombre de méthodes définies directement sur l'objet produit par le groupby

In [170]:
methods = [x for x in dir(g) if not x.startswith('_')]
f"Le type {type(g).__name__} expose {len(methods)} méthodes."

'Le type SeriesGroupBy expose 66 méthodes.'

In [171]:
columns = 7
nb_methods = len(methods)
nb_pad = (columns - nb_methods % columns) % columns

array = np.array(methods + nb_pad * ['']).reshape((columns, -1))

In [172]:
pd.DataFrame(data=array.transpose())

,0,1,2,3,4,5,6
0,agg,cummax,filter,is_monotonic_increasing,nlargest,rank,tail
1,aggregate,cummin,first,kurt,nsmallest,resample,take
2,all,cumprod,get_group,last,nth,rolling,transform
3,any,cumsum,groups,max,nunique,sample,unique
4,apply,describe,head,mean,ohlc,sem,value_counts
5,bfill,diff,hist,median,pct_change,shift,var
6,corr,dtype,idxmax,min,pipe,size,
7,count,ewm,idxmin,ndim,plot,skew,
8,cov,expanding,indices,ngroup,prod,std,
9,cumcount,ffill,is_monotonic_decreasing,ngroups,quantile,sum,

La méthode `aggregate` (dont l’alias est `agg`) est la méthode, qui permet d’appliquer une fonction (ou liste de fonctions) à chaque groupe avec la possibilité d’appliquer une fonction à une colonne spécifique du groupe.

In [173]:
numeric_columns = tips.describe().columns

tips.groupby('day')[numeric_columns].agg(['mean', 'std'])

     total_bill       tip      size
           mean  std mean  std mean  std
day
Thur      17.68 7.89 2.77 1.24 2.45 1.07
Fri       17.15 8.30 2.73 1.02 2.11 0.57
Sat       20.44 9.48 2.99 1.63 2.52 0.82
Sun       21.41 8.83 3.26 1.23 2.84 1.01

In [174]:
tips.groupby('day')[numeric_columns].agg([np.mean, np.std])

     total_bill       tip      size
           mean  std mean  std mean  std
day
Thur      17.68 7.82 2.77 1.23 2.45 1.06
Fri       17.15 8.08 2.73 0.99 2.11 0.55
Sat       20.44 9.43 2.99 1.62 2.52 0.81
Sun       21.41 8.77 3.26 1.23 2.84 1.00

In [175]:
tips.groupby('day').agg({'tip': np.mean, 'total_bill': np.std})

      tip  total_bill
day
Thur 2.77        7.82
Fri  2.73        8.08
Sat  2.99        9.43
Sun  3.26        8.77

In [176]:
d = pd.DataFrame({'key': list('ABCABC'), 
                  'val1': range(6),
                  'val2' : range(100, 106)})
d

  key  val1  val2
0   A     0   100
1   B     1   101
2   C     2   102
3   A     3   103
4   B     4   104
5   C     5   105

In [177]:
d.groupby('key').sum()

     val1  val2
key
A       3   203
B       5   205
C       7   207

In [178]:
d.groupby('key').filter(lambda x: x['val1'].sum() > 3)

  key  val1  val2
1   B     1   101
2   C     2   102
4   B     4   104
5   C     5   105

In [179]:
r = np.random.normal(0.5, 2, 4)
r

array([ 1.24183651,  4.29952131, -1.65130566, -0.40519115])

In [180]:
d = pd.DataFrame({'key': list('ab'*2), 'data': r,'data2': r*2})
d

  key  data  data2
0   a  1.24   2.48
1   b  4.30   8.60
2   a -1.65  -3.30
3   b -0.41  -0.81

In [181]:
g = d.groupby('key')

Je centre chaque groupe par rapport à sa moyenne

In [182]:
g.transform(lambda x: x - x.mean())

   data  data2
0  1.45   2.89
1  2.35   4.70
2 -1.45  -2.89
3 -2.35  -4.70

## Faire pivoter un DataFrame avec ``

In [185]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.00,1,0,53.10,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.00,0,0,8.05,S,Third,man,True,NaN,Southampton,no,True

In [187]:
titanic.pivot_table('survived',
                    index='class',
                    columns='sex')

sex     female  male
class
First     0.97  0.37
Second    0.92  0.16
Third     0.50  0.14

In [188]:
titanic.pivot_table('survived',
                    index='class',
                    columns='sex',
                    aggfunc=np.mean)

sex     female  male
class
First     0.97  0.37
Second    0.92  0.16
Third     0.50  0.14